name = "PrincipalMomentAnalysis"
uuid = "8f9a47b0-6b96-11e9-187c-53db488c4ade"
authors = ["Rasmus Henningsson <rasmus.henningsson@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
