name = "PrincipalMomentsAnalysis"
uuid = "6a3ba550-3b7f-11e9-2734-d9178ad1e8db"
authors = ["Rasmus Henningsson <rasmus.henningsson@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
